name: tests

on:
  repository_dispatch:
    types: [test]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' }}
    name: testing on ${{ matrix.platform }} 
    timeout-minutes: 360
    steps:
      - name: Test notebook/s
        shell: bash
        run: |
          docker run -t ghcr.io/${{ github.repository }}:dev bash -c " \
            mkdir us5; \
            cd us5; \
            ln -s ../data/md5.rst md.rst; \
            bash ../scripts/setup_umb_samp.sh; \
            bash run_umb_samp.sh; \
            wait; \
            cpptraj < ../data/make_us_trj.in &> make_us_trj.log; \
            wait; \
            cd ..; \
            mkdir adiab5; \
            cd adiab5; \
            ln -s ../us5/rc-0.30/md1ps.rst md1ps_rc-0.3.rst; \
            bash ../scripts/run_adiab_all.sh; \
            wait; \
            cpptraj < ../data/make_adiab_trj.in &> make_adiab_trj.log; \
            wait; \
            pip install pytest nbmake; \
            find . -name '*.ipynb' | pytest --nbmake --nbmake-timeout=3600; "

  tag-release:
    runs-on: ubuntu-24.04
    name: tag release
    needs:
      - tests
    steps:
      - name: Authenticate with GHCR
        id: auth
        uses: docker/login-action@v3.5.0
        with:
          registry: "ghcr.io"
          username: ${{github.actor}}
          password: ${{secrets.BUILD_TOKEN}}

      - name: Push new tags
        shell: bash
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ github.event.client_payload.tag }} \
            ghcr.io/${{ github.repository }}:dev
